name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy-site-x
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Write Kamal Secrets File
        run: |
          mkdir -p .kamal
          echo "KAMAL_REGISTRY_PASSWORD=$KAMAL_REGISTRY_PASSWORD" > .kamal/secrets
        env:
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.CICD_PAT_TOKEN }}

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Start tailscaled
        run: |
          sudo mkdir -p /var/run/tailscale
          sudo tailscaled --socket=/var/run/tailscale/tailscaled.sock &
          sleep 5

      - name: Authenticate Tailscale
        run: |
          sudo tailscale --socket=/var/run/tailscale/tailscaled.sock up \
            --authkey=${{ secrets.TAILSCALE_AUTH_KEY }}
            
      - name: Install Kamal
        run: sudo gem install kamal

      - name: Deploy
        run: kamal deploy -v
        env:
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.CICD_PAT_TOKEN}}